SysInventarioFacturacion.UI.AppWebAspNetCore/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using SysInventarioFacturacion.EntidadesDeNegocio;
using SysInventarioFacturacion.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace SysInventarioFacturacion.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    [Authorize(Roles = "SuperAdmin")]
    public class CategoriaController : Controller
    {
        CategoriaBL CategoriaBL = new CategoriaBL();
        // GET: CategoriaController
        public async Task<IActionResult> Index(Categoria? pCategoria = null)
        {
            if (pCategoria == null)
                pCategoria = new Categoria();
            if (pCategoria.Top_Aux == 0)
                pCategoria.Top_Aux = 10;
            else if (pCategoria.Top_Aux == -1)
                pCategoria.Top_Aux = 0;
            var Categoria = await CategoriaBL.BuscarAsync(pCategoria);
            ViewBag.Top = pCategoria.Top_Aux;
            return View(Categoria);
        }

        // GET: CategoriaController/Details/5
        public async Task<IActionResult> Details(int IdCategoria)
        {
            var Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(new Categoria { IdCategoria = IdCategoria });
            return View(Categoria);
        }

        // GET: CategoriaController/Create
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: CategoriaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Categoria pCategoria)
        {
            try
            {
                int result = await CategoriaBL.CrearAsync(pCategoria);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCategoria);
            }
        }

        // GET: CategoriaController/Edit/5
        public async Task<IActionResult> Edit(Categoria pCategoria)
        {
            var Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(pCategoria);
            ViewBag.Error = "";
            return View(Categoria);
        }

        // POST: CategoriaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdCategoria, Categoria pCategoria)
        {
            try
            {
                int result = await CategoriaBL.ModificarAsync(pCategoria);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCategoria);
            }
        }

        // GET: CategoriaController/Delete/5
        public async Task<IActionResult> Delete(Categoria pCategoria)
        {
            var Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(pCategoria);
            return View(Categoria);
        }

        // POST: CategoriaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int IdCategoria, Categoria pCategoria)
        {
            try
            {
                int result = await CategoriaBL.EliminarAsync(pCategoria);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCategoria);
            }
        }
    }
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using SysInventarioFacturacion.EntidadesDeNegocio;
using SysInventarioFacturacion.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.EntityFrameworkCore;
using SysInventarioFacturacion.AccesoADatos;

namespace SysInventarioFacturacion.UI.AppWebAspNetCore.Controllers
{
	[Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class ProductoController : Controller
	{
		ProductoBL ProductoBL = new ProductoBL();
		CategoriaBL CategoriaBL = new CategoriaBL();
		ProveedorBL ProveedorBL = new ProveedorBL();

		// GET: ProductoController
		public async Task<IActionResult> Index(Producto? pProducto = null)
		{
			if (pProducto == null)
				pProducto = new Producto();
			if (pProducto.Top_Aux == 0)
				pProducto.Top_Aux = 10;
			else if (pProducto.Top_Aux == -1)
				pProducto.Top_Aux = 0;
			var taskBuscar = ProductoBL.BuscarIncluirCategoriayProveedorAsync(pProducto);
			var taskObtenerTodosCategoria = CategoriaBL.ObtenerTodosAsync();
			var taskObtenerTodosProveedor = ProveedorBL.ObtenerTodosAsync();
			var Productos = await taskBuscar;
			ViewBag.Categoria = await taskObtenerTodosCategoria;
			ViewBag.Proveedor = await taskObtenerTodosProveedor;
			ViewBag.Top = pProducto.Top_Aux;
			return View(Productos);
		}

		// GET: ProductoController/Details/5
		public async Task<IActionResult> Details(int IdProducto)
		{
			var producto = await ProductoBL.ObtenerPorIdProductoAsync(new Producto { IdProducto = IdProducto });
			producto.Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(new Categoria { IdCategoria = producto.IdCategoria });
			producto.Proveedor = await ProveedorBL.ObtenerPorIdAsync(new Proveedor { IdProveedor = producto.IdProveedor });
			return View(producto);
		}

		// GET: ProductoController/Create

		public async Task<IActionResult> Create()
		{
			ViewBag.Categoria = await CategoriaBL.ObtenerTodosAsync();
			ViewBag.Proveedor = await ProveedorBL.ObtenerTodosAsync();
			ViewBag.Error = "";
			return View();
		}

		// POST: ProductoController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(Producto pProducto)
		{
			try
			{
				int result = await ProductoBL.CrearAsync(pProducto);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				ViewBag.Categoria = await CategoriaBL.ObtenerTodosAsync();
				ViewBag.Proveedor = await ProveedorBL.ObtenerTodosAsync();
				ViewBag.Error = ex.Message;
				return View(pProducto);
			}
		}

		// GET: ProductoController/Edit/5
		public async Task<IActionResult> Edit(Producto pProducto)
		{
			var taskObtenerPorIdProducto = ProductoBL.ObtenerPorIdProductoAsync(pProducto);
			var taskObtenerTodosCategoria = CategoriaBL.ObtenerTodosAsync();
			var taskObtenerTodosProveedor = ProveedorBL.ObtenerTodosAsync();
			var producto = await taskObtenerPorIdProducto;
			ViewBag.Categoria = await taskObtenerTodosCategoria;
			ViewBag.Proveedor = await taskObtenerTodosProveedor;
			ViewBag.Error = "";
			return View(producto);
		}

		// POST: ProductoController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int IdProducto, Producto pProducto)
		{
			try
			{
				int result = await ProductoBL.ModificarAsync(pProducto);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				ViewBag.Error = ex.Message;
				ViewBag.Categoria = await CategoriaBL.ObtenerTodosAsync();
				ViewBag.Proveedor = await ProveedorBL.ObtenerTodosAsync();
				return View(pProducto);
			}
		}

		// GET: ProductoController/Delete/5
		public async Task<IActionResult> Delete(Producto pProducto)
		{
			var Producto = await ProductoBL.ObtenerPorIdProductoAsync(pProducto);
            Producto.Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(new Categoria { IdCategoria = Producto.IdCategoria });
            Producto.Proveedor = await ProveedorBL.ObtenerPorIdAsync(new Proveedor { IdProveedor = Producto.IdProveedor });
			ViewBag.Error = "";
			return View(Producto);
		}

		// POST: ProductoController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(int IdProducto, Producto pProducto)
		{
			try
			{
				int result = await ProductoBL.EliminarAsync(pProducto);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				ViewBag.Error = ex.Message;
				var producto = await ProductoBL.ObtenerPorIdProductoAsync(pProducto);
				if (producto == null)
                    producto = new Producto();
				if (producto.IdProducto > 0)
                    producto.Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(new Categoria { IdCategoria = producto.IdCategoria });
				if (producto.IdProducto > 0)
                    producto.Proveedor = await ProveedorBL.ObtenerPorIdAsync(new Proveedor { IdProveedor = producto.IdProveedor });
				return View(producto);
			}
		}

        public async Task<IActionResult> Inventario(Producto? pProducto = null)
        {
            if (pProducto == null)
                pProducto = new Producto();
            if (pProducto.Top_Aux == 0)
                pProducto.Top_Aux = 10;
            else if (pProducto.Top_Aux == -1)
                pProducto.Top_Aux = 0;
            var taskBuscar = ProductoBL.BuscarIncluirCategoriayProveedorAsync(pProducto);
            var taskObtenerTodosCategoria = CategoriaBL.ObtenerTodosAsync();
            var taskObtenerTodosProveedor = ProveedorBL.ObtenerTodosAsync();
            var Productos = await taskBuscar;
            ViewBag.Categoria = await taskObtenerTodosCategoria;
            ViewBag.Proveedor = await taskObtenerTodosProveedor;
            ViewBag.Top = pProducto.Top_Aux;
            return View(Productos);
        }


        // POST: ProductoController/Edit/5
        public async Task<IActionResult> EditExistencia(Producto pProducto)
        {
            var taskObtenerPorIdProducto = ProductoBL.ObtenerPorIdProductoAsync(pProducto);
            var taskObtenerTodosCategoria = CategoriaBL.ObtenerTodosAsync();
            var taskObtenerTodosProveedor = ProveedorBL.ObtenerTodosAsync();
            var producto = await taskObtenerPorIdProducto;
            ViewBag.Categoria = await taskObtenerTodosCategoria;
            ViewBag.Proveedor = await taskObtenerTodosProveedor;
            ViewBag.Error = "";
            return View(producto);
        }

        // POST: ProductoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditExistencia(int IdProducto, Producto pProducto)
        {
            try
            {
                int result = await ProductoBL.ModificarExistenciasAsync(pProducto);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Categoria = await CategoriaBL.ObtenerTodosAsync();
                ViewBag.Proveedor = await ProveedorBL.ObtenerTodosAsync();
                return View(pProducto);
            }
        }
       
        
         
        


    }
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Controllers/ProveedorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using SysInventarioFacturacion.EntidadesDeNegocio;
using SysInventarioFacturacion.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;



namespace SysInventarioFacturacion.UI.AppWebAspNetCore.Controllers

{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    [Authorize(Roles = "SuperAdmin")]
    public class ProveedorController : Controller
    {    
        ProveedorBL ProveedorBL = new ProveedorBL();
        // GET: ProveedorController
        public async Task<IActionResult> Index(Proveedor pProveedor = null)
        {
            if (pProveedor == null)
               pProveedor = new Proveedor();
            if (pProveedor.Top_Aux == 0)
                pProveedor.Top_Aux = 10;
            else if (pProveedor.Top_Aux == -1)
                pProveedor.Top_Aux = 0;
            var proveedores= await ProveedorBL.BuscarAsync(pProveedor);
            ViewBag.Top = pProveedor.Top_Aux;
            return View(proveedores);
        }

        // GET: ProveedorController/Details/5
        public async Task<IActionResult> Details(int IdProveedor)
        {
            var proveedor = await ProveedorBL.ObtenerPorIdAsync(new Proveedor { IdProveedor = IdProveedor });
            return View(proveedor);
        }

        // GET: ProveedorController/Create
        public  IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: ProveedorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Proveedor pProveedor)
        {
            try
            {   
                int result = await ProveedorBL.CrearAsync(pProveedor);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pProveedor);
            }
        }

        // GET: ProveedorController/Edit/5
        public async Task<IActionResult> Edit(Proveedor pProveedor)
        {
            var proveedor = await ProveedorBL.ObtenerPorIdAsync(pProveedor);
            ViewBag.Error = "";
            return View(proveedor);
        }

        // POST: ProveedorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdProveedor, Proveedor pProveedor)
        {
            try
            {
                int result = await ProveedorBL.ModificarAsync(pProveedor);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {   
                ViewBag.Error = ex.Message;
                return View(pProveedor);
            }
        }

        // GET: ProveedorController/Delete/5
        public async Task<IActionResult> Delete(Proveedor pProveedor)
        {
            var proveedor = await ProveedorBL.ObtenerPorIdAsync(pProveedor);
            return View(proveedor);
        }

        // POST: ProveedorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int IdProveedor, Proveedor pProveedor)
        {
            try
            {   
                int result = await ProveedorBL.EliminarAsync(pProveedor);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {   
                ViewBag.Error = ex.Message;
                return View(pProveedor);
            }
        }
    }
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Views/Producto/Create.cshtml
@model SysInventarioFacturacion.EntidadesDeNegocio.Producto

@{
    ViewData["Title"] = "Create";
    List<SysInventarioFacturacion.EntidadesDeNegocio.Categoria> categorias = ViewBag.Categoria as List<SysInventarioFacturacion.EntidadesDeNegocio.Categoria>;
    List<SysInventarioFacturacion.EntidadesDeNegocio.Proveedor> proveedores = ViewBag.Proveedor as List<SysInventarioFacturacion.EntidadesDeNegocio.Proveedor>;

}

<h1>Agregar Un Nuevo Producto</h1>
<hr />

<div>
    <button class="btn btn-primary" style="background-color: #0074D9;">
        <a asp-area="" asp-controller="Categoria" asp-action="Create" style="color: white; text-decoration: none;">
            <i class="fas fa-plus"></i> Categoria
        </a>
    </button>

    <button class="btn btn-success" style="background-color: #005626;">
        <a asp-area="" asp-controller="Proveedor" asp-action="Create" style="color: white; text-decoration: none;">
            <i class="fas fa-plus"></i> Proveedor
        </a>
    </button>
</div>



<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">

        <div class="col-md-4">
            <div class="form-group ">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Talla" class="control-label"></label>
                <input asp-for="Talla" class="form-control" />
                <span asp-validation-for="Talla" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group ">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group ">
                    <label asp-for="Color" class="control-label"></label>
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>
            </div>



            <div class="col-md-4">
                <div class="form-group ">
                    <label asp-for="PrecioUnitario" class="control-label"></label>
                    <input asp-for="PrecioUnitario" class="form-control" />
                    <span asp-validation-for="PrecioUnitario" class="text-danger"></span>
                </div>
            </div>

            @* RELACIONES BOTONES DESPLEGABLAS*@

            <div class="col-md-4">
                <div class="form-group ">
                    <label asp-for="Proveedor" class="control-label"></label>

                    <select asp-for="IdProveedor" class="form-control">
                        <option selected value="">SELECCIONAR</option>
                        @foreach (var item in proveedores)
                        {
                            <option value="@item.IdProveedor">@item.Nombre</option>
                        }
                    </select>
                    <span asp-validation-for="IdProveedor" class="text-danger"></span>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group ">
                    <label asp-for="Categoria" class="control-label"></label>

                    <select asp-for="IdCategoria" class="form-control">
                        <option selected value="">SELECCIONAR</option>
                        @foreach (var item in categorias)
                        {
                            <option value="@item.IdCategoria">@item.Nombre</option>
                        }
                    </select>
                    <span asp-validation-for="IdCategoria" class="text-danger"></span>
                </div>
            </div>
        </div>

        @*BOTONES EDITADOS CON ICONOS*@

        <div class="form-group" style="margin-top: 10px;">
            <button type="submit" class="btn btn-success" style="margin-right: 10px;">
                <i class="fas fa-save"></i> Guardar
            </button>

            <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
                <i class="fas fa-times"></i> Cancelar
            </button>
        </div>

        <span class="text-danger">@ViewBag.Error</span>

    </div>

</form>

@section Scripts
    {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Views/Producto/Delete.cshtml
@model SysInventarioFacturacion.EntidadesDeNegocio.Producto

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Producto</h1>

<h3>¿ Esta seguro que desea eliminar ?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Talla)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Talla)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioUnitario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrecioUnitario)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdCategoria)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Categoria.Nombre)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdProveedor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Proveedor.Nombre)
        </dd>
    </dl>

    @* FUNCTION ELIMINAR PRODUCTO*@
    @using (Html.BeginForm("Delete", "Producto", new { IdProducto = Model.IdProducto }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <button type="submit" class="btn btn-danger" onclick="return confirm('¿Está seguro de eliminar?');" style="margin-left: 10px;">
            <i class="fas fa-trash"></i> Eliminar
        </button>

        <button type="button" class="btn btn-secondary" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
            <i class="fas fa-times"></i> Cancelar
        </button>
    }

</div>

SysInventarioFacturacion.UI.AppWebAspNetCore/Views/Producto/Details.cshtml
@model SysInventarioFacturacion.EntidadesDeNegocio.Producto

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles Producto</h1>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Talla)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Talla)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioUnitario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrecioUnitario)
        </dd>
    </dl>

    <dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.IdCategoria)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Categoria.Nombre)
    </dd>
    </dl>
        <dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.IdProveedor)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Proveedor.Nombre)
    </dd>
    </dl>
</div>

             @*BOTONES EDITADOS CON ICONOS*@

<td class="botonestabla">
    <button type="button" class="btn btn-success" style="background-color: #264DA0; color: white; margin-right: 10px;" onclick="window.location.href='@Url.Action("Edit", new { IdProducto = Model.IdProducto })'">
        <i class="fas fa-pencil-alt"></i> Ir a Modificar
    </button>
</td>

<td class="botonestabla">
    <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
        <i class="fas fa-times"></i> Cancelar
    </button>
</td>