SysInventarioFacturacion.UI.AppWebAspNetCore/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using SysInventarioFacturacion.EntidadesDeNegocio;
using SysInventarioFacturacion.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace SysInventarioFacturacion.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    [Authorize(Roles = "SuperAdmin")]
    public class CategoriaController : Controller
    {
        CategoriaBL CategoriaBL = new CategoriaBL();
        // GET: CategoriaController
        public async Task<IActionResult> Index(Categoria? pCategoria = null)
        {
            if (pCategoria == null)
                pCategoria = new Categoria();
            if (pCategoria.Top_Aux == 0)
                pCategoria.Top_Aux = 10;
            else if (pCategoria.Top_Aux == -1)
                pCategoria.Top_Aux = 0;
            var Categoria = await CategoriaBL.BuscarAsync(pCategoria);
            ViewBag.Top = pCategoria.Top_Aux;
            return View(Categoria);
        }

        // GET: CategoriaController/Details/5
        public async Task<IActionResult> Details(int IdCategoria)
        {
            var Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(new Categoria { IdCategoria = IdCategoria });
            return View(Categoria);
        }

        // GET: CategoriaController/Create
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: CategoriaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Categoria pCategoria)
        {
            try
            {
                int result = await CategoriaBL.CrearAsync(pCategoria);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCategoria);
            }
        }

        // GET: CategoriaController/Edit/5
        public async Task<IActionResult> Edit(Categoria pCategoria)
        {
            var Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(pCategoria);
            ViewBag.Error = "";
            return View(Categoria);
        }

        // POST: CategoriaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdCategoria, Categoria pCategoria)
        {
            try
            {
                int result = await CategoriaBL.ModificarAsync(pCategoria);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCategoria);
            }
        }

        // GET: CategoriaController/Delete/5
        public async Task<IActionResult> Delete(Categoria pCategoria)
        {
            var Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(pCategoria);
            return View(Categoria);
        }

        // POST: CategoriaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int IdCategoria, Categoria pCategoria)
        {
            try
            {
                int result = await CategoriaBL.EliminarAsync(pCategoria);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCategoria);
            }
        }
    }
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Controllers/FacturaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using SysInventarioFacturacion.EntidadesDeNegocio;
using SysInventarioFacturacion.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using SysInventarioFacturacion.AccesoADatos;

namespace SysInventarioFacturacion.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    [Authorize(Roles = "Cajero,SuperAdmin")]
    
    public class FacturaController : Controller
    {
        FacturaBL FacturaBL = new FacturaBL();
        UsuarioBL UsuarioBL = new UsuarioBL();
        // GET: FacturaController
        public async Task<IActionResult> Index(Factura pFactura = null)
        {
            if (pFactura == null)
                pFactura = new Factura();
            if (pFactura.Top_Aux == 0)
                pFactura.Top_Aux = 10;
            else if (pFactura.Top_Aux == -1)
                pFactura.Top_Aux = 0;
            var taskBuscar = FacturaBL.BuscarIncluirUsuarioAsync(pFactura);
            var taskObtenerTodosUsuarios = UsuarioBL.ObtenerTodosAsync();
            var Facturas = await taskBuscar;
            ViewBag.Top = pFactura.Top_Aux;
            ViewBag.Usuarios = await taskObtenerTodosUsuarios;
            return View(Facturas);
        }

        // GET: FacturaController/Details/5
        public async Task<IActionResult> Details(int IdFactura)
        {
            var factura = await FacturaBL.ObtenerPorIdAsync(new Factura { IdFactura = IdFactura });
            factura.Usuario = await UsuarioBL.ObtenerPorIdAsync(new Usuario { Id = factura.IdUsuario });
            return View(factura);
        }

        // GET: FacturaController/Create
        
        public async Task<IActionResult> Create()
        {
            ViewBag.Usuarios = await UsuarioBL.ObtenerTodosAsync();
            ViewBag.Error = "";
            return View();
        }

        // POST: FacturaController/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Factura pFactura)
        {
            try
            {
                int result = await FacturaBL.CrearAsync(pFactura);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Usuarios = await UsuarioBL.ObtenerTodosAsync();
                return View(pFactura);
            }
        }

        // GET: FacturaController/Edit/5
        public async Task<IActionResult> Edit(Factura pFactura)
        {
            var taskObtenerPorId = FacturaBL.ObtenerPorIdAsync(pFactura);
            var taskObtenerTodosUsuarios = UsuarioBL.ObtenerTodosAsync();
            var factura = await taskObtenerPorId;
            ViewBag.Usuarios = await taskObtenerTodosUsuarios;
            ViewBag.Error = "";
            return View(factura);
        }

        // POST: FacturaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdFactura, Factura pFactura)
        {
            try
            {
                int result = await FacturaBL.ModificarAsync(pFactura);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Usuarios = await UsuarioBL.ObtenerTodosAsync();
                return View(pFactura);
            }
        }

        // GET: FacturaController/Delete/5
        public async Task<IActionResult> Delete(Factura pFactura)
        {
            var Factura = await FacturaBL.ObtenerPorIdAsync(pFactura);
            Factura.Usuario = await UsuarioBL.ObtenerPorIdAsync(new Usuario { Id = Factura.IdUsuario });
            ViewBag.Error = "";

            return View(Factura);
        }

        // POST: FacturaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int IdFactura, Factura pFactura)
        {
            try
            {
                int result = await FacturaBL.EliminarAsync(pFactura);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                var factura = await FacturaBL.ObtenerPorIdAsync(pFactura);
                if (factura == null)
                    factura = new Factura();
                if (factura.IdFactura > 0)
                    factura.Usuario = await UsuarioBL.ObtenerPorIdAsync(new Usuario { Id = factura.IdUsuario });
                return View(factura);
            }
        }
    }
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using SysInventarioFacturacion.EntidadesDeNegocio;
using SysInventarioFacturacion.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using SysInventarioFacturacion.AccesoADatos;

namespace SysInventarioFacturacion.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    [Authorize(Roles = "SuperAdmin")]
    public class PedidoController : Controller
	{
		PedidoBL PedidoBL = new PedidoBL();
		UsuarioBL UsuarioBL = new UsuarioBL();
		// GET: FacturaController
		public async Task<IActionResult> Index(Pedido pPedido = null)
		{
			if (pPedido == null)
				pPedido = new Pedido();
			if (pPedido.Top_Aux == 0)
				pPedido.Top_Aux = 10;
			else if (pPedido.Top_Aux == -1)
				pPedido.Top_Aux = 0;
			var taskBuscar = PedidoBL.BuscarIncluirUsuarioAsync(pPedido);
			var taskObtenerTodosUsuarios = UsuarioBL.ObtenerTodosAsync();
			var Pedidos = await taskBuscar;
			ViewBag.Top = pPedido.Top_Aux;
			ViewBag.Usuarios = await taskObtenerTodosUsuarios;
			return View(Pedidos);
		}

		// GET: FacturaController/Details/5
		public async Task<IActionResult> Details(int IdPedido)
		{
			var pedido = await PedidoBL.ObtenerPorIdAsync(new Pedido { IdPedido = IdPedido });
			pedido.Usuario = await UsuarioBL.ObtenerPorIdAsync(new Usuario { Id = pedido.IdUsuario });
			return View(pedido);
		}

		// GET: FacturaController/Create

		public async Task<IActionResult> Create()
		{
			ViewBag.Usuarios = await UsuarioBL.ObtenerTodosAsync();
			ViewBag.Error = "";
			return View();
		}

		// POST: FacturaController/Create

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(Pedido pPedido)
		{
			try
			{
				int result = await PedidoBL.CrearAsync(pPedido);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
                ViewBag.Usuarios = await UsuarioBL.ObtenerTodosAsync();
                ViewBag.Error = ex.Message;
				return View(pPedido);
			}
		}

		// GET: FacturaController/Edit/5
		public async Task<IActionResult> Edit(Pedido pPedido)
		{
			var taskObtenerPorId = PedidoBL.ObtenerPorIdAsync(pPedido);
			var taskObtenerTodosUsuarios = UsuarioBL.ObtenerTodosAsync();
			var pedido = await taskObtenerPorId;
			ViewBag.Usuarios = await taskObtenerTodosUsuarios;
			ViewBag.Error = "";
			return View(pedido);
		}

		// POST: FacturaController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int IdPedido, Pedido pPedido)
		{
			try
			{
				int result = await PedidoBL.ModificarAsync(pPedido);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				ViewBag.Error = ex.Message;
				ViewBag.Usuarios = await UsuarioBL.ObtenerTodosAsync();
				return View(pPedido);
			}
		}

		// GET: FacturaController/Delete/5
		public async Task<IActionResult> Delete(Pedido pPedido)
		{
			var Pedido = await PedidoBL.ObtenerPorIdAsync(pPedido);
			Pedido.Usuario = await UsuarioBL.ObtenerPorIdAsync(new Usuario { Id = Pedido.IdUsuario });
			ViewBag.Error = "";

			return View(Pedido);
		}

		// POST: FacturaController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(int IdPedido, Pedido pPedido)
		{
			try
			{
				int result = await PedidoBL.EliminarAsync(pPedido);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				ViewBag.Error = ex.Message;
				var pedido = await PedidoBL.ObtenerPorIdAsync(pPedido);
				if (pedido == null)
					pedido = new Pedido();
				if (pedido.IdPedido > 0)
					pedido.Usuario = await UsuarioBL.ObtenerPorIdAsync(new Usuario { Id = pedido.IdUsuario });
				return View(pedido);
			}
		}
	}
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Controllers/RolController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using SysInventarioFacturacion.EntidadesDeNegocio;
using SysInventarioFacturacion.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace SysInventarioFacturacion.UI.AppWebAspNetCore.Controllers
{
   [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class RolController : Controller
    {
        RolBL rolBL = new RolBL();
        // GET: RolController
        public async Task<IActionResult> Index(Rol pRol = null)
        {
            if (pRol == null)
                pRol = new Rol();
            if (pRol.Top_Aux == 0)
                pRol.Top_Aux = 10;
            else if (pRol.Top_Aux == -1)
                pRol.Top_Aux = 0;
            var roles = await rolBL.BuscarAsync(pRol);
            ViewBag.Top = pRol.Top_Aux;
            return View(roles);
        }

        // GET: RolController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var rol = await rolBL.ObtenerPorIdAsync(new Rol { Id = id });
            return View(rol);
        }

        // GET: RolController/Create
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: RolController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Rol pRol)
        {
            try
            {
                int result = await rolBL.CrearAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }

        // GET: RolController/Edit/5
        public async Task<IActionResult> Edit(Rol pRol)
        {
            var rol = await rolBL.ObtenerPorIdAsync(pRol);
            ViewBag.Error = "";
            return View(rol);
        }

        // POST: RolController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Rol pRol)
        {
            try
            {
                int result = await rolBL.ModificarAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }

        // GET: RolController/Delete/5
        public async Task<IActionResult> Delete(Rol pRol)
        {
            ViewBag.Error = "";
            var rol = await rolBL.ObtenerPorIdAsync(pRol);
            return View(rol);
        }

        // POST: RolController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Rol pRol)
        {
            try
            {
                int result = await rolBL.EliminarAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }
    }
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventario y Facturacion</title>
    <!--    https://fontawesome.com/   -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.19.0/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Incluye jQuery desde el CDN de Google -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    @*Link para iconos*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-......" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Home.css">
    <link rel="stylesheet" href="~/css/Menu.css">
    <link rel="stylesheet" href="~/css/Inicio.css">
    <link rel="stylesheet" href="~/css/Venta.css">
   

</head>

<body>
    <header>
        <label class="labelMenu"><i class="fa fa-bars"></i></label>
    </header>
    <header>
        @{
            string? nombre = User.Identity.Name;
            int? Idu = global.idu;

        }


    </header>
    <div class="menu">
        <h1><i class="fa fa-address-card"></i></h1>
        <nav>
            <ul>
                <div class="logo-container">
                    <!-- Aquí puedes agregar el código o la imagen del logotipo de tu empresa -->
                    <!-- Por ejemplo, si es una imagen: -->
                    <img src="~/IMG/ZeroStresLogo.png" alt="Logo de la empresa" class="logo-container">
                </div>

                <li class="Nombre">
                    <a class="dashboard-nav-dropdown-item-nombre">Bienvenido @nombre </a>
                  
                </li>

                @if (User.IsInRole("SuperAdmin"))
                {
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Index">Usuario</a>
                    </li>

                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Rol" asp-action="Index">Rol</a>
                    </li>

                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Producto" asp-action="Index">Producto</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Producto" asp-action="Inventario">Inventario</a>
                    </li>

                    <li class="nav-item">
                        <a class="dashboard-nav-item" asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a>
                    </li>
                     <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Factura" asp-action="Index">Factura</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Proveedor" asp-action="Index">Proveedor</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="DetalleFactura" asp-action="Index">DetalleFactura</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="DetalleFactura" asp-action="Venta">Venta</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="DetalleFactura" asp-action="Reportes">Reportes</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Pedido" asp-action="Index">Pedido</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="DetallePedido" asp-action="Index">DetallePedido</a>
                    </li>

                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Usuario" asp-action="CambiarPassword">Cambiar password</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-item" asp-area="" asp-controller="Usuario" asp-action="CerrarSesion">Cerrar sesión</a>
                    </li>


                }
                else
                {
                    <li class="nav-item">
                        <a class="dashboard-nav-item" asp-area="" asp-controller="Usuario" asp-action="CerrarSesion">Cerrar sesión</a>
                    </li>
                }
                @if (User.IsInRole("Cajero"))
                {
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="DetalleFactura" asp-action="Venta">Venta</a>
                    </li>
                    
                }
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="DetalleFactura" asp-action="Venta">Venta</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Producto" asp-action="Inventario">Inventario</a>
                    </li>
                }
            </ul>
           
                
        </nav>
    </div>
    <div class="opacMenu"></div>

    <!--  Jquery  -->
    <div class='dashboard-content'>
        <div class='dashboard-app'>
            <div class='container'>
                <main role="main" class="pb-2">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">New message</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Send message</button>
                </div>
            </div>
        </div>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/Inicio.js"></script>
    <script src="~/js/Venta.js"></script>
    <script src="~/js/Menu.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/JavaScriptHome.js" asp-append-version="true"></script>
 
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>