SysInventarioFacturacion.UI.AppWebAspNetCore/Controllers/DetalleFacturaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using SysInventarioFacturacion.EntidadesDeNegocio;
using SysInventarioFacturacion.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using SysInventarioFacturacion.AccesoADatos;
using SysInventarioFacturacion.UI.AppWebAspNetCore.Models;



namespace SysInventarioFacturacion.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    [Authorize(Roles = "Cajero,SuperAdmin,Admin")]
    public class DetalleFacturaController : Controller
    {
        DetalleFacturaBL detalle_facturaBL = new DetalleFacturaBL();
        FacturaBL FacturaBL = new FacturaBL();
        ProductoBL ProductoBL = new ProductoBL();
        public static int idFac;

        // GET: RolController
        public async Task<IActionResult> Index(DetalleFactura pDetalleFactura = null)
        {
            if (pDetalleFactura == null)
                pDetalleFactura = new DetalleFactura();
            if (pDetalleFactura.Top_Aux == 0)
                pDetalleFactura.Top_Aux = 10;
            else if (pDetalleFactura.Top_Aux == -1)
                pDetalleFactura.Top_Aux = 0;
            var taskBuscar = detalle_facturaBL.BuscarIncluirFacturasYProductoAsync(pDetalleFactura);
            var taskObtenerTodosFacturas = FacturaBL.ObtenerTodosAsync();
            var taskObtenerTodosProducto = ProductoBL.ObtenerTodosAsync();
            var DetalleFacturas = await taskBuscar;
            ViewBag.Top = pDetalleFactura.Top_Aux;
            ViewBag.Facturas = await taskObtenerTodosFacturas;
            ViewBag.Producto = await taskObtenerTodosProducto;
            return View(DetalleFacturas);
        }

        // GET: DetalleFacturaController/Details/5
        public async Task<IActionResult> Details(int IdDetalleFactura)
        {
            var detalleFactura = await detalle_facturaBL.ObtenerPorIdAsync(new DetalleFactura { IdDetalleFactura = IdDetalleFactura });
            detalleFactura.Factura = await FacturaBL.ObtenerPorIdAsync(new Factura { IdFactura = detalleFactura.IdFactura });
            detalleFactura.Producto = await ProductoBL.ObtenerPorIdProductoAsync(new Producto { IdProducto = detalleFactura.IdProducto });
            return View(detalleFactura);
        }



        // GET: DetalleFacturaController/Create


        public async Task<IActionResult> Create()
        {
            ViewBag.Facturas = await FacturaBL.ObtenerTodosAsync();
            ViewBag.Producto = await ProductoBL.ObtenerTodosAsync();
            ViewBag.Error = "";
            return View();
        }
        // POST: DeatlleFacturaController/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DetalleFactura pDetalleFactura)
        {
            try
            {
                int result = await detalle_facturaBL.CrearAsync(pDetalleFactura);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Facturas = await FacturaBL.ObtenerTodosAsync();
                ViewBag.Producto = await ProductoBL.ObtenerTodosAsync();
                return View(pDetalleFactura);
            }
        }

        // GET: DeatlleFacturaController/Edit/5
        public async Task<IActionResult> Edit(DetalleFactura pDetalleFactura)
        {
            var taskObtenerPorId = detalle_facturaBL.ObtenerPorIdAsync(pDetalleFactura);
            var taskObtenerTodosFacturas = FacturaBL.ObtenerTodosAsync();
            var taskObtenerTodosProducto = ProductoBL.ObtenerTodosAsync();
            var detalleFactura = await taskObtenerPorId;
            ViewBag.Facturas = await taskObtenerTodosFacturas;
            ViewBag.Producto = await taskObtenerTodosProducto;
            ViewBag.Error = "";
            return View(detalleFactura);
        }

        // POST: DetalleFacturaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdDetalleFactura, DetalleFactura pDetalleFactura)
        {
            try
            {
                int result = await detalle_facturaBL.ModificarAsync(pDetalleFactura);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Facturas = await FacturaBL.ObtenerTodosAsync();
                ViewBag.Producto = await ProductoBL.ObtenerTodosAsync();
                return View(pDetalleFactura);
            }
        }

        // GET: DetalleFacturaController/Delete/5
        public async Task<IActionResult> Delete(DetalleFactura pDetalleFactura)
        {
            var DetalleFactura = await detalle_facturaBL.ObtenerPorIdAsync(pDetalleFactura);
            DetalleFactura.Factura = await FacturaBL.ObtenerPorIdAsync(new Factura { IdFactura = DetalleFactura.IdFactura });
            DetalleFactura.Producto = await ProductoBL.ObtenerPorIdProductoAsync(new Producto { IdProducto = DetalleFactura.IdProducto });
            ViewBag.Error = "";

            return View(DetalleFactura);
        }

        // POST: DetalleFacturaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, DetalleFactura pDetalleFactura)
        {
            try
            {
                int result = await detalle_facturaBL.EliminarAsync(pDetalleFactura);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                var detalleFactura = await detalle_facturaBL.ObtenerPorIdAsync(pDetalleFactura);
                if (detalleFactura == null)
                    detalleFactura = new DetalleFactura();
                if (detalleFactura.IdDetalleFactura > 0)
                    detalleFactura.Factura = await FacturaBL.ObtenerPorIdAsync(new Factura { IdFactura = detalleFactura.IdFactura });
                if (detalleFactura.IdDetalleFactura > 0)
                    detalleFactura.Producto = await ProductoBL.ObtenerPorIdProductoAsync(new Producto { IdProducto = detalleFactura.IdProducto });
                return View(detalleFactura);
            }
        }
        List<DetalleFactura>? DetalleFacturas;
        public async Task<IActionResult> Venta(int? campo, DetalleFactura pDetalleFactura = null)
        {
            if (pDetalleFactura == null)
                pDetalleFactura = new DetalleFactura();
            if (pDetalleFactura.Top_Aux == 0)
                pDetalleFactura.Top_Aux = 10;
            else if (pDetalleFactura.Top_Aux == -1)
                pDetalleFactura.Top_Aux = 0;
            var taskBuscar = detalle_facturaBL.BuscarIncluirFacturasYProductoAsync(pDetalleFactura);
            var taskObtenerTodosFacturas = FacturaBL.ObtenerTodosAsync();
            var taskObtenerTodosProducto = ProductoBL.ObtenerTodosAsync();
            DetalleFacturas = await taskBuscar;
            ViewBag.Top = pDetalleFactura.Top_Aux;
            ViewBag.Facturas = await taskObtenerTodosFacturas;

            if (campo > 0)
            {
                Producto producto = new Producto();
                producto.Codigo = campo;
                List<Producto> ProductoBuscado = await ProductoBL.BuscarAsync(producto);
                ViewBag.Producto = ProductoBuscado;
            }
            else
            {
                ViewBag.Producto = await taskObtenerTodosProducto;
            }
            return View(DetalleFacturas);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DetalleVenta(DetalleFactura pDetalleFactura)
        {
            try
            {
                int result = await detalle_facturaBL.CrearAsync(pDetalleFactura);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Facturas = await FacturaBL.ObtenerTodosAsync();
                ViewBag.Producto = await ProductoBL.ObtenerTodosAsync();
                return View(pDetalleFactura);
            }
        }
        // GET: DetalleFacturaController/Create

        public async Task<IActionResult> DetalleVenta()
        {
            ViewBag.Facturas = await FacturaBL.ObtenerTodosAsync();
            ViewBag.Producto = await ProductoBL.ObtenerTodosAsync();
            ViewBag.Error = "";
            return View();
        }



        //[HttpPost("ProcesarFactura")]
        //public JsonResult ProcesarFactura([Bind("NumeroFactura, Descripcion, Direccion, Telefono, Correo, total, descuento, impuesto, totalpagado, FechaFacturacion, detalleFacturas")] int NumeroFactura, string Descripcion, string Direccion, string Correo, string Telefono, decimal total, decimal descuento, decimal impuesto, decimal totalpagado, List<DetalleFactura> detalleFacturas)
        //{
        //    Random random = new Random();


        //    Factura objFactura = new Factura();
        //    objFactura.IdUsuario = global.idu;
        //    objFactura.NumeroFactura = random.Next(100000, 999999);
        //    objFactura.Descripcion = Descripcion;
        //    objFactura.Direccion = Direccion;
        //    objFactura.Correo = Correo;
        //    objFactura.Total = total;
        //    objFactura.Descuento = descuento;
        //    objFactura.Impuesto = impuesto;
        //    objFactura.TotalPagado = totalpagado;

        //    objFactura.Telefono = Telefono;



        //    objFactura.FechaFacturacion = DateTime.Now;

SysInventarioFacturacion.UI.AppWebAspNetCore/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using SysInventarioFacturacion.EntidadesDeNegocio;
using SysInventarioFacturacion.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.EntityFrameworkCore;
using SysInventarioFacturacion.AccesoADatos;

namespace SysInventarioFacturacion.UI.AppWebAspNetCore.Controllers
{
	[Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class ProductoController : Controller
	{
		ProductoBL ProductoBL = new ProductoBL();
		CategoriaBL CategoriaBL = new CategoriaBL();
		ProveedorBL ProveedorBL = new ProveedorBL();

		// GET: ProductoController
		public async Task<IActionResult> Index(Producto? pProducto = null)
		{
			if (pProducto == null)
				pProducto = new Producto();
			if (pProducto.Top_Aux == 0)
				pProducto.Top_Aux = 10;
			else if (pProducto.Top_Aux == -1)
				pProducto.Top_Aux = 0;
			var taskBuscar = ProductoBL.BuscarIncluirCategoriayProveedorAsync(pProducto);
			var taskObtenerTodosCategoria = CategoriaBL.ObtenerTodosAsync();
			var taskObtenerTodosProveedor = ProveedorBL.ObtenerTodosAsync();
			var Productos = await taskBuscar;
			ViewBag.Categoria = await taskObtenerTodosCategoria;
			ViewBag.Proveedor = await taskObtenerTodosProveedor;
			ViewBag.Top = pProducto.Top_Aux;
			return View(Productos);
		}

		// GET: ProductoController/Details/5
		public async Task<IActionResult> Details(int IdProducto)
		{
			var producto = await ProductoBL.ObtenerPorIdProductoAsync(new Producto { IdProducto = IdProducto });
			producto.Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(new Categoria { IdCategoria = producto.IdCategoria });
			producto.Proveedor = await ProveedorBL.ObtenerPorIdAsync(new Proveedor { IdProveedor = producto.IdProveedor });
			return View(producto);
		}

		// GET: ProductoController/Create

		public async Task<IActionResult> Create()
		{
			ViewBag.Categoria = await CategoriaBL.ObtenerTodosAsync();
			ViewBag.Proveedor = await ProveedorBL.ObtenerTodosAsync();
			ViewBag.Error = "";
			return View();
		}

		// POST: ProductoController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(Producto pProducto)
		{
			try
			{
				int result = await ProductoBL.CrearAsync(pProducto);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				ViewBag.Categoria = await CategoriaBL.ObtenerTodosAsync();
				ViewBag.Proveedor = await ProveedorBL.ObtenerTodosAsync();
				ViewBag.Error = ex.Message;
				return View(pProducto);
			}
		}

		// GET: ProductoController/Edit/5
		public async Task<IActionResult> Edit(Producto pProducto)
		{
			var taskObtenerPorIdProducto = ProductoBL.ObtenerPorIdProductoAsync(pProducto);
			var taskObtenerTodosCategoria = CategoriaBL.ObtenerTodosAsync();
			var taskObtenerTodosProveedor = ProveedorBL.ObtenerTodosAsync();
			var producto = await taskObtenerPorIdProducto;
			ViewBag.Categoria = await taskObtenerTodosCategoria;
			ViewBag.Proveedor = await taskObtenerTodosProveedor;
			ViewBag.Error = "";
			return View(producto);
		}

		// POST: ProductoController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int IdProducto, Producto pProducto)
		{
			try
			{
				int result = await ProductoBL.ModificarAsync(pProducto);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				ViewBag.Error = ex.Message;
				ViewBag.Categoria = await CategoriaBL.ObtenerTodosAsync();
				ViewBag.Proveedor = await ProveedorBL.ObtenerTodosAsync();
				return View(pProducto);
			}
		}

		// GET: ProductoController/Delete/5
		public async Task<IActionResult> Delete(Producto pProducto)
		{
			var Producto = await ProductoBL.ObtenerPorIdProductoAsync(pProducto);
            Producto.Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(new Categoria { IdCategoria = Producto.IdCategoria });
            Producto.Proveedor = await ProveedorBL.ObtenerPorIdAsync(new Proveedor { IdProveedor = Producto.IdProveedor });
			ViewBag.Error = "";
			return View(Producto);
		}

		// POST: ProductoController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(int IdProducto, Producto pProducto)
		{
			try
			{
				int result = await ProductoBL.EliminarAsync(pProducto);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				ViewBag.Error = ex.Message;
				var producto = await ProductoBL.ObtenerPorIdProductoAsync(pProducto);
				if (producto == null)
                    producto = new Producto();
				if (producto.IdProducto > 0)
                    producto.Categoria = await CategoriaBL.ObtenerPorIdCategoriaAsync(new Categoria { IdCategoria = producto.IdCategoria });
				if (producto.IdProducto > 0)
                    producto.Proveedor = await ProveedorBL.ObtenerPorIdAsync(new Proveedor { IdProveedor = producto.IdProveedor });
				return View(producto);
			}
		}

        public async Task<IActionResult> Inventario(Producto? pProducto = null)
        {
            if (pProducto == null)
                pProducto = new Producto();
            if (pProducto.Top_Aux == 0)
                pProducto.Top_Aux = 10;
            else if (pProducto.Top_Aux == -1)
                pProducto.Top_Aux = 0;
            var taskBuscar = ProductoBL.BuscarIncluirCategoriayProveedorAsync(pProducto);
            var taskObtenerTodosCategoria = CategoriaBL.ObtenerTodosAsync();
            var taskObtenerTodosProveedor = ProveedorBL.ObtenerTodosAsync();
            var Productos = await taskBuscar;
            ViewBag.Categoria = await taskObtenerTodosCategoria;
            ViewBag.Proveedor = await taskObtenerTodosProveedor;
            ViewBag.Top = pProducto.Top_Aux;
            return View(Productos);
        }


        // POST: ProductoController/Edit/5
        public async Task<IActionResult> EditExistencia(Producto pProducto)
        {
            var taskObtenerPorIdProducto = ProductoBL.ObtenerPorIdProductoAsync(pProducto);
            var taskObtenerTodosCategoria = CategoriaBL.ObtenerTodosAsync();
            var taskObtenerTodosProveedor = ProveedorBL.ObtenerTodosAsync();
            var producto = await taskObtenerPorIdProducto;
            ViewBag.Categoria = await taskObtenerTodosCategoria;
            ViewBag.Proveedor = await taskObtenerTodosProveedor;
            ViewBag.Error = "";
            return View(producto);
        }

        // POST: ProductoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditExistencia(int IdProducto, Producto pProducto)
        {
            try
            {
                int result = await ProductoBL.ModificarExistenciasAsync(pProducto);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Categoria = await CategoriaBL.ObtenerTodosAsync();
                ViewBag.Proveedor = await ProveedorBL.ObtenerTodosAsync();
                return View(pProducto);
            }
        }
       
        
         
        


    }
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="row">
    <div class="action-card">
        <img src="~/IMG/Usuario-removebg-preview.png" alt="Descripción de la imagen">
        <a asp-area="" asp-controller="Usuario" asp-action="Create">Agregar Usuario</a>
    </div>
    <div class="action-card">
        <img src="~/IMG/ZapatoIcon-removebg-preview.png" alt="Descripción de la imagen">
        <a asp-area="" asp-controller="Producto" asp-action="Create">Agregar Producto</a>
    </div>
    <div class="action-card">
        <img src="~/IMG/Carritocompra-removebg-preview.png" alt="Descripción de la imagen">
        <a asp-area="" asp-controller="DetalleFactura" class="action-card-button" asp-action="Venta">Crear Venta</a>
    </div>
    <div class="action-card">
        <img src="~/IMG/LOS_REPORTES-removebg-preview.png" alt="Descripción de la imagen">
        <a asp-area="" asp-controller="DetalleFactura" asp-action="Reportes">Ver Reportes</a>
    </div>
</div>
<div class="row">

    <div class="carousel-container">
        <!-- Carrusel 1 -->
        <div class="carousel">
            <div class="slides">
                <img src="https://i.pinimg.com/564x/21/08/c7/2108c7a95bdcd52611b7577fcced6fd2.jpg" alt="Slide A" class="slide">
                <img src="https://i.pinimg.com/564x/0d/e4/eb/0de4eb8418d8dc6839f5b9c4b9be2545.jpg" alt="Slide A" class="slide">
                <img src="https://i.pinimg.com/564x/16/1c/03/161c03335947bcc4e5df7b5995d7eea9.jpg" alt="Slide A" class="slide">
            </div>
            <div class="controls">
                <div class="control prev-slide">&#9668;</div>
                <div class="control next-slide">&#9658;</div>
            </div>
        </div>
    </div>

    <div class="carousel-container">
        <!-- Carrusel 2 -->
        <div class="carousel">
            <div class="slides">
                <img src="https://i.pinimg.com/564x/8d/c3/bd/8dc3bd131684479d7f7eabcaef2a2953.jpg" alt="Slide A" class="slide">
                <img src="https://i.pinimg.com/564x/87/c6/92/87c69225f953289e5aa44e87d2f2ede4.jpg" alt="Slide A" class="slide">
                <img src="https://i.pinimg.com/564x/5b/73/c5/5b73c5a26b4a88eccdfaac036486d827.jpg" alt="Slide A" class="slide">
            </div>
            <div class="controls">
                <div class="control prev-slide">&#9668;</div>
                <div class="control next-slide">&#9658;</div>
            </div>
        </div>
    </div>

    <div class="carousel-container">
        <!-- Carrusel 3 -->
        <div class="carousel">
            <div class="slides">
                <img src="https://i.pinimg.com/564x/08/cc/1d/08cc1d19e601d13fcc08f07894adf1e0.jpg" alt="Slide A" class="slide">
                <img src="https://i.pinimg.com/564x/43/f3/95/43f3955be8d2e02ecfbf301f45e58c98.jpg" alt="Slide A" class="slide">
                <img src="https://i.pinimg.com/564x/6d/d3/71/6dd371df5e7cd7299409b1529f81feee.jpg" alt="Slide A" class="slide">
            </div>
            <div class="controls">
                <div class="control prev-slide">&#9668;</div>
                <div class="control next-slide">&#9658;</div>
            </div>
        </div>
    </div>

    <!--Tarjetas-->
</div>

<div>

    <div class="sneaker-card">
                    <img class="sneaker-profile-pic" src="https://images.unsplash.com/photo-1608667508764-33cf0726b13a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8c25lYWtlcnN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60" />
        <h2 >
            Nike
        </h2>

    </div>

    <div class="sneaker-card">
        <img class="sneaker-profile-pic" src="https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fHNuZWFrZXJzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" />
        <h2>Nike</h2>
    </div>

    <div class="sneaker-card">
        <img class="sneaker-profile-pic" src="https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fHNuZWFrZXJzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" />
        <h2>Nike</h2>
    </div>

    <div class="sneaker-card">
        <img class="sneaker-profile-pic" src="https://images.unsplash.com/photo-1586525198428-225f6f12cff5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHNuZWFrZXJzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" />
        <h2>Nike</h2>
    </div>

    <div class="sneaker-card">
        <img class="sneaker-profile-pic" src="https://i.pinimg.com/564x/5f/09/39/5f0939e1b062380bd338a344a9f8a4ea.jpg" />
        <h2>Puma</h2>
    </div>

    <div class="sneaker-card">
        <img class="sneaker-profile-pic" src="https://i.pinimg.com/564x/57/be/ca/57beca4106ed0ccc591c7c405d22996d.jpg" />
        <h2>Nike</h2>
    </div>


</div>