SysInventarioFacturacion.UI.AppWebAspNetCore/Controllers/DetallePedidoController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SysInventarioFacturacion.EntidadesDeNegocio;
using SysInventarioFacturacion.LogicaDeNegocio;

namespace SysInventarioFacturacion.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    [Authorize(Roles = "SuperAdmin")]

    public class DetallePedidoController : Controller
    {

        DetallePedidoBL DetallePedidoBL = new DetallePedidoBL();
        ProductoBL ProductoBL = new ProductoBL();
        ProveedorBL ProveedorBL = new ProveedorBL();
        PedidoBL PedidoBL = new PedidoBL();
        // GET: DetallePedidoController
        public async Task<IActionResult> Index(DetallePedido pDetallePedido = null)
        {
            if (pDetallePedido == null)
                pDetallePedido = new DetallePedido();
            if (pDetallePedido.Top_Aux == 0)
                pDetallePedido.Top_Aux = 10;
            else if (pDetallePedido.Top_Aux == -1)
                pDetallePedido.Top_Aux = 0;
            var taskBuscar = DetallePedidoBL.BuscarIncluirPedidoProductoProveedorAsync(pDetallePedido);
            var taskObtenerTodosPedido = PedidoBL.ObtenerTodosAsync();
            var taskObtenerTodosProducto = ProductoBL.ObtenerTodosAsync();
            var taskObtenerTodosProveedor = ProveedorBL.ObtenerTodosAsync();
            var DetallePedido = await taskBuscar;
            ViewBag.Top = pDetallePedido.Top_Aux;
            ViewBag.Pedido = await taskObtenerTodosPedido;
            ViewBag.Proveedor = await taskObtenerTodosProveedor;
            ViewBag.Producto = await taskObtenerTodosProducto;
            return View(DetallePedido);
        }

        // GET: DetallePedidoController/Details/5
        public async Task<IActionResult> Details(int IdDetallePedido)
        {
            var DetallePedido = await DetallePedidoBL.ObtenerPorIdAsync(new DetallePedido { IdDetallePedido = IdDetallePedido });
            DetallePedido.Pedido = await PedidoBL.ObtenerPorIdAsync(new Pedido { IdPedido = DetallePedido.IdPedido });
            DetallePedido.Proveedor = await ProveedorBL.ObtenerPorIdAsync(new Proveedor { IdProveedor = DetallePedido.IdProveedor });
            DetallePedido.Producto = await ProductoBL.ObtenerPorIdProductoAsync(new Producto { IdProducto = DetallePedido.IdProducto });
            
            return View(DetallePedido);
        }

        // GET: DetallePedidoController/Create

        public async Task<IActionResult> Create()
        {
            ViewBag.Pedido = await PedidoBL.ObtenerTodosAsync();
            ViewBag.Producto = await ProductoBL.ObtenerTodosAsync();
            ViewBag.Proveedor = await ProveedorBL.ObtenerTodosAsync();
            ViewBag.Error = "";
            return View();
        }

        // POST: DetallePedidoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DetallePedido pDetallePedido)
        {
            try
            {
                int result = await DetallePedidoBL.CrearAsync(pDetallePedido);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Pedido = await PedidoBL.ObtenerTodosAsync();
                ViewBag.Producto = await ProductoBL.ObtenerTodosAsync();
                ViewBag.Proveedor = await ProveedorBL.ObtenerTodosAsync();
                return View(pDetallePedido);
            }
        }

        // GET: DetallePedidoController/Edit/5
        public async Task<IActionResult> Edit(DetallePedido pDetallePedido)
        {
            var taskObtenerPorId = DetallePedidoBL.ObtenerPorIdAsync(pDetallePedido);
            var taskObtenerTodosPedido = PedidoBL.ObtenerTodosAsync();
            var taskObtenerTodosProveedor = ProveedorBL.ObtenerTodosAsync();
            var taskObtenerTodosProducto = ProductoBL.ObtenerTodosAsync();
            var DetallePedido = await taskObtenerPorId;
            ViewBag.Pedido = await taskObtenerTodosPedido;
            ViewBag.Producto = await taskObtenerTodosProducto;
            ViewBag.Proveedor = await taskObtenerTodosProveedor;
            ViewBag.Error = "";
            return View(DetallePedido);
        }

        // POST: DetallePedidoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdDetallePedido, DetallePedido pDetallePedido)
        {
            try
            {
                int result = await DetallePedidoBL.ModificarAsync(pDetallePedido);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Pedido = await PedidoBL.ObtenerTodosAsync();
                ViewBag.Producto = await ProductoBL.ObtenerTodosAsync();
                ViewBag.Proveedor = await ProveedorBL.ObtenerTodosAsync();
                return View(pDetallePedido);
            }
        }

        // GET: DetallePedidoController/Delete/5
        public async Task<IActionResult> Delete(DetallePedido pDetallePedido)
        {
            var DetallePedido = await DetallePedidoBL.ObtenerPorIdAsync(pDetallePedido);
            DetallePedido.Pedido = await PedidoBL.ObtenerPorIdAsync(new Pedido { IdPedido = DetallePedido.IdPedido });
            DetallePedido.Producto = await ProductoBL.ObtenerPorIdProductoAsync(new Producto { IdProducto = DetallePedido.IdProducto });
            DetallePedido.Proveedor = await ProveedorBL.ObtenerPorIdAsync(new Proveedor { IdProveedor = DetallePedido.IdProveedor });
            ViewBag.Error = "";

            return View(DetallePedido);
        }

        // POST: DetallePedidoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, DetallePedido pDetallePedido)
        {
            try
            {
                int result = await DetallePedidoBL.EliminarAsync(pDetallePedido);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                var DetallePedido = await DetallePedidoBL.ObtenerPorIdAsync(pDetallePedido);
                if (DetallePedido == null)
                    DetallePedido = new DetallePedido();
                if (DetallePedido.IdDetallePedido > 0)
                    DetallePedido.Pedido = await PedidoBL.ObtenerPorIdAsync(new Pedido { IdPedido = DetallePedido.IdPedido });
                if (DetallePedido.IdDetallePedido > 0)
                    DetallePedido.Producto = await ProductoBL.ObtenerPorIdProductoAsync(new Producto { IdProducto = DetallePedido.IdProducto });
                if (DetallePedido.IdDetallePedido > 0)
                    DetallePedido.Proveedor = await ProveedorBL.ObtenerPorIdAsync(new Proveedor { IdProveedor = DetallePedido.IdProveedor });
                return View(DetallePedido);
            }
        }
    }
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Views/DetallePedido/Create.cshtml
@model SysInventarioFacturacion.EntidadesDeNegocio.DetallePedido

@{
    ViewData["Title"] = "Create";
    List<SysInventarioFacturacion.EntidadesDeNegocio.Pedido> pedidos = ViewBag.Pedido as List<SysInventarioFacturacion.EntidadesDeNegocio.Pedido>;
    List<SysInventarioFacturacion.EntidadesDeNegocio.Producto> productos = ViewBag.Producto as List<SysInventarioFacturacion.EntidadesDeNegocio.Producto>;
    List<SysInventarioFacturacion.EntidadesDeNegocio.Proveedor> proveedores = ViewBag.Proveedor as List<SysInventarioFacturacion.EntidadesDeNegocio.Proveedor>;

}

<h1>Crear</h1>

<h4>Detalle Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="IdPedido" class="control-label"></label>
                        <select asp-for="IdPedido" class="form-control">
                            <option selected value="">SELECCIONAR</option>
                            @foreach (var item in pedidos)
                            {
                                <option value="@item.IdPedido">@item.IdPedido</option>
                            }
                        </select>
                        <span asp-validation-for="IdPedido" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="IdProducto" class="control-label"></label>
                        <select asp-for="IdProducto" class="form-control">
                            <option selected value="">SELECCIONAR</option>
                            @foreach (var item in productos)
                            {
                                <option value="@item.IdProducto">@item.Nombre</option>
                            }
                        </select>
                        <span asp-validation-for="IdProducto" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="IdProveedor" class="control-label"></label>
                        <select asp-for="IdProveedor" class="form-control">
                            <option selected value="">SELECCIONAR</option>
                            @foreach (var item in proveedores)
                            {
                                <option value="@item.IdProveedor">@item.Nombre</option>
                            }
                        </select>
                        <span asp-validation-for="IdProveedor" class="text-danger"></span>
                    </div>
                </div>
            </div>

            @*BOTONES EDITADOS CON ICONOS*@

            <div class="form-group" style="margin-top: 10px;">
                <button type="submit" class="btn btn-success" style="margin-right: 10px;">
                    <i class="fas fa-save"></i> Guardar
                </button>

                <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
                    <i class="fas fa-times"></i> Cancelar
                </button>
            </div>

            <span class="text-danger">@ViewBag.Error</span>

        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Views/DetallePedido/Delete.cshtml
@model SysInventarioFacturacion.EntidadesDeNegocio.DetallePedido

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>¿Esta seguro que desea eliminar?</h3>
<div>
    <h4>Detalle Pedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdDetallePedido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdDetallePedido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPedido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPedido)
        </dd>
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProducto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Producto.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPedido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPedido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proveedor.Nombre)
        </dd>
    </dl>

    @* FUNCTION ELIMINAR DETALLE PEDIDO*@
    @using (Html.BeginForm("Delete", "DetallePedido", new { IdDetallePedido = Model.IdDetallePedido }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <button type="submit" class="btn btn-danger" onclick="return confirm('¿Está seguro que desea eliminar?');" style="margin-left: 10px;">
            <i class="fas fa-trash"></i> Eliminar
        </button>

        <button type="button" class="btn btn-secondary" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
            <i class="fas fa-times"></i> Cancelar
        </button>
    }

</div>

SysInventarioFacturacion.UI.AppWebAspNetCore/Views/DetallePedido/Details.cshtml
@model SysInventarioFacturacion.EntidadesDeNegocio.DetallePedido

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles de</h1>

<div>
    <h4>Detalle Pedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPedido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPedido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProducto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Producto.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPedido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPedido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proveedor.Nombre)
        </dd>
    </dl>
</div>

@*BOTONES EDITADOS CON ICONOS*@

<td class="botonestabla">
    <button type="button" class="btn btn-success" style="background-color: #264DA0; color: white; margin-right: 10px;" onclick="window.location.href='@Url.Action("Edit", new { IdDetallePedido = Model.IdDetallePedido })'">
        <i class="fas fa-pencil-alt"></i> Ir a Modificar
    </button>
</td>

<td class="botonestabla">
    <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
        <i class="fas fa-times"></i> Cancelar
    </button>
</td>

SysInventarioFacturacion.UI.AppWebAspNetCore/Views/DetallePedido/Edit.cshtml
@model SysInventarioFacturacion.EntidadesDeNegocio.DetallePedido

@{
    ViewData["Title"] = "Edit";
    List<SysInventarioFacturacion.EntidadesDeNegocio.Pedido> pedidos = ViewBag.Pedido as List<SysInventarioFacturacion.EntidadesDeNegocio.Pedido>;
    List<SysInventarioFacturacion.EntidadesDeNegocio.Producto> productos = ViewBag.Producto as List<SysInventarioFacturacion.EntidadesDeNegocio.Producto>;
    List<SysInventarioFacturacion.EntidadesDeNegocio.Proveedor> proveedores = ViewBag.Proveedor as List<SysInventarioFacturacion.EntidadesDeNegocio.Proveedor>;
}

<h1>Modificar</h1>

<h4>Detalle Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdDetallePedido" class="form-control" />
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>

            <div class="row">

                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="IdProducto" class="control-label"></label>
                        <select asp-for="IdProducto" class="form-control">
                            <option selected value="">SELECCIONAR</option>
                            @foreach (var item in productos)
                            {
                                if (Model.IdProducto == item.IdProducto)
                                {
                                    <option selected value="@item.IdProducto">@item.Nombre</option>
                                }
                                else
                                {
                                    <option value="@item.IdProducto">@item.Nombre</option>
                                }
                            }
                        </select>
                        <span asp-validation-for="IdProducto" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="IdPedido" class="control-label"></label>
                        <select asp-for="IdPedido" class="form-control">
                            <option selected value="">SELECCIONAR</option>
                            @foreach (var item in pedidos)
                            {
                                if (Model.IdPedido == item.IdPedido)
                                {
                                    <option selected value="@item.IdPedido">@item.IdPedido</option>
                                }
                                else
                                {
                                    <option value="@item.IdPedido">@item.IdPedido</option>
                                }
                            }
                        </select>
                        <span asp-validation-for="IdPedido" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="IdProveedor" class="control-label"></label>
                        <select asp-for="IdProveedor" class="form-control">
                            <option selected value="">SELECCIONAR</option>
                            @foreach (var item in proveedores)
                            {
                                if (Model.IdProveedor == item.IdProveedor)
                                {
                                    <option selected value="@item.IdProveedor">@item.Nombre</option>
                                }
                                else
                                {
                                    <option value="@item.IdProveedor">@item.IdProveedor</option>
                                }
                            }
                        </select>
                        <span asp-validation-for="IdProveedor" class="text-danger"></span>
                    </div>
                </div>
            </div>

            @*BOTONES EDITADOS CON ICONOS*@

            <div class="form-group" style="margin-top: 10px;">
                <button type="submit" class="btn btn-success" style="margin-right: 10px;">
                    <i class="fas fa-save"></i> Guardar
                </button>

                <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
                    <i class="fas fa-times"></i> Cancelar
                </button>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SysInventarioFacturacion.UI.AppWebAspNetCore/Views/DetallePedido/Index.cshtml
@model IEnumerable<SysInventarioFacturacion.EntidadesDeNegocio.DetallePedido>

@{
    ViewData["Title"] = "Index";
    int numPage = 1;
    int numRegistros = 0;
    int numRegistrosPorPage = 10;
    int[] tops = { 10, 20, 50, 100, 500, 1000, 10000, -1 };
    int topActual = Convert.ToInt32(ViewBag.Top);
    List<SysInventarioFacturacion.EntidadesDeNegocio.Pedido> pedidos = ViewBag.Pedido as List<SysInventarioFacturacion.EntidadesDeNegocio.Pedido>;
    List<SysInventarioFacturacion.EntidadesDeNegocio.Producto> productos = ViewBag.Producto as List<SysInventarioFacturacion.EntidadesDeNegocio.Producto>;
    List<SysInventarioFacturacion.EntidadesDeNegocio.Proveedor> proveedores = ViewBag.Proveedor as List<SysInventarioFacturacion.EntidadesDeNegocio.Proveedor>;

}

<h1>Buscar</h1>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Index">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Proveedor</label>
                        <select name="IdProveedor" class="form-control">
                            <option selected value="0">SELECCIONAR</option>
                            @foreach (var item in proveedores)
                            {
                                <option value="@item.IdProveedor">@item.Nombre</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Producto</label>
                        <select name="IdProducto" class="form-control">
                            <option selected value="0">SELECCIONAR</option>
                            @foreach (var item in productos)
                            {
                                <option value="@item.IdProducto">@item.Nombre</option>
                            }
                        </select>
                    </div>
                </div>
            </div>

           @* BOTONES DE BUSCAR Y CREAR DETALLE PEDIDO*@
           
            <div class="form-group" style="margin-top: 10px;">
                <button type="submit" class="btn btn-primary" style="background-color: #0074D9; color: white;">
                    <i class="fas fa-search"></i> Buscar
                </button>


                <button type="button" class="btn btn-success" onclick="window.location.href='@Url.Action("Create")'">
                    <i class="fas fa-plus"></i> Agregar
                </button>
            </div>

        </form>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaPedido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdProducto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdPedido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdProveedor)
            </th>
            <th colspan="3">Acciones</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Cantidad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaPedido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdPedido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Proveedor.Nombre)
                </td>
                @*BOTONES CRUD EDITAR - LEER - ELIMINAR DETALLE PEDIDO*@


                <td class="botonestabla">
                    <button type="button" class="btn btn-primary" style="background-color: #264DA0; color: white" onclick="window.location.href='@Url.Action("Edit", new { IdDetallePedido = item.IdDetallePedido })'">
                        <i class="fas fa-pencil-alt"></i> Modificar
                    </button>
                </td>


                <td class="botonestabla">
                    <button type="button" class="btn btn-info" onclick="window.location.href='@Url.Action("Details", new { IdDetallePedido = item.IdDetallePedido })'">
                        <i class="fas fa-eye"></i> Detalles
                    </button>
                </td>
                <td class="botonestabla">
                    <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Delete", new { IdDetallePedido = item.IdDetallePedido })'">
                        <i class="fas fa-trash"></i> Eliminar
                    </button>
                </td>
            </tr>

            numRegistros++;
            if (numRegistros == numRegistrosPorPage)
            {
                numPage++;
                numRegistros = 0;
            }
        }
        @{
            if (numRegistros == 0)
            {
                numPage--;
            }
        }
    </tbody>
</table>
@if (numPage > 1)
{
    <div class="row" style="overflow:auto">
        <div class="col-md-12">
            <ul class="pagination paginationjs" data-numpage="@numPage" data-pageactive="1">
                <li class="page-item" data-typepage="Previous"><a class="page-link" href="#">Previous</a></li>
                @for (var i = 1; i <= numPage; i++)
                {
                    <li class="page-item" data-page="@i" data-typepage="Item"><a class="page-link" href="#">@i</a></li>
                }
                <li class="page-item" data-typepage="Next"><a class="page-link" href="#">Next</a></li>
            </ul>
        </div>
    </div>
}